default: &default
 adapter: postgresql
 username: tweeter
 password: <%= ENV['POSTGRES_DB_PASSWORD'] %>
 host: localhost
 pool: <%= ENV["DB_POOL"] || ENV['MAX_THREADS'] || 25 %>

development:
 <<: *default
 database: tweeter
